---
title: "DAR F21 Project Status Notebook Template"
author: "Student Name"
date: "TBD"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
subtitle: "DAR Project Name (Eat4Genes or DeFi)"
---

## Instructions (DELETE BEFORE SUBMISSION)

* Use this notebook is a template for your biweekly project status assignment. 
* Use the sections starting with **BiWeekly Work Summary** as your outline for your submitted notebook.
* Summarize ALL of your work in this notebook; **if you don't show and/or link to your work here, it doesn't exist for us!**

1. Create a new copy of this notebook in the `AssignmentX` sub-directory of your team's github repository using the following naming convention

   * `rcsid_assignmentX.Rmd` and `rcsid_assignmentX.pdf`
   * For example, `bennek_assignment03.Rmd`

2. Document **all** the work you did on your assigned project this week **using the outline below.** 

3. You MUST include figures and/or tables to illustrate your work. *Screen shots are okay*, but include something!

4. You MUST include links to other important resources (knitted HTMl files, Shiny apps). See the guide below for help.

5. Commit the source (`.Rmd`) and knitted (`.html`) versions of your notebook and push to github

6. **Submit a pull request.** Please notify Dr. Erickson if you don't see your notebook merged within one day. 

7. **DO NOT MERGE YOUR PULL REQUESTS YOURSELF!!**

See the Grading Rubric for guidance on how the contents of this notebook will be graded on lms. 


### Guide to linking to Shiny Apps

* On the cluster, create a sub-directory called `ShinyApps` in your home directory

    * In RStudio in the **Terminal** tab, `cd ~`
    * Then `mkdir ShinyApps`
    * You only need to do this once
    
* In your new `ShinyApps` sub-directory, create a sub-directory to contain your app

    * In the **Terminal** tab, `cd ~/ShinyApps` 
    * Then `mkdir yourcoolapp` (if `yourcoolapp` is the name of your app)
    * Then copy all of the files associated with your app (esp. the `app.R`) in that directory
    
* Alternatively, you can create a symbolic link in that directory, "pointing" to your working directory. In this way your shared app will always be up-to-date.

    * In the **Terminal** tab, `cd ~/ShinyApps` 
    * Then (for example) `ln -s /home/yourrcs/yourappdirectory yourcoolapp` 

* You can now share your app on the RPI network using this syntax:

    * `http://lp01.idea.rpi.edu/shiny/yourrcs/yourcoolapp/` 

## Weekly Work Summary	

**NOTE:** Follow an outline format; use bullets to express individual points. 

* RCS ID: **Always** include this!
* Project Name: **Always** include this!
* Summary of work since last week 

    * Describe the important aspects of what you worked on and accomplished

* NEW: Summary of github issues added and worked 

    * Issues that you've submitted
    * Issues that you've self-assigned and addressed
    
* Summary of github commits 

    * include branch name(s)
    * include browsable links to all external files on github
    * Include links to shared Shiny apps
    
* List of presentations,  papers, or other outputs

    * Include browsable links
    
* List of references (if necessary) 
* Indicate any use of group shared code base
* Indicate which parts of your described work were done by you or as part of joint efforts

## Personal Contribution	

* Clearly defined, unique contribution(s) done by you: code, ideas, writing...
* Include github issues you've addressed

## Discussion of Primary Findings 	

* Discuss primary findings: 

    * What did you want to know? 
    * How did you go about finding it? 
    * What did you find?
	
* **Required:** Provide illustrating figures and/or tables
     
    * Embed your code in this notebook if possible.
    * If not possible, screen shots are acceptable. 
    * If your figures are "live," either include source code embedded in notebook or provide github location for their source scripts.
    * If your contributions included things that are not done in an R-notebook, (e.g. researching, writing, and coding in Python), you still need to do this status notebook in R.  Describe what you did here and put any products that you created in github. If you are writing online documents (e.g. overleaf or google docs), you can include links to the documents in this notebook instead of actual text.
  ****
